package com.lost.zou.pedometer.data.model.database.core;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pedometerCardEntityDaoConfig;
    private final DaoConfig calendarCardEntityDaoConfig;

    private final PedometerCardEntityDao pedometerCardEntityDao;
    private final CalendarCardEntityDao calendarCardEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pedometerCardEntityDaoConfig = daoConfigMap.get(PedometerCardEntityDao.class).clone();
        pedometerCardEntityDaoConfig.initIdentityScope(type);

        calendarCardEntityDaoConfig = daoConfigMap.get(CalendarCardEntityDao.class).clone();
        calendarCardEntityDaoConfig.initIdentityScope(type);

        pedometerCardEntityDao = new PedometerCardEntityDao(pedometerCardEntityDaoConfig, this);
        calendarCardEntityDao = new CalendarCardEntityDao(calendarCardEntityDaoConfig, this);

        registerDao(PedometerCardEntity.class, pedometerCardEntityDao);
        registerDao(CalendarCardEntity.class, calendarCardEntityDao);
    }
    
    public void clear() {
        pedometerCardEntityDaoConfig.getIdentityScope().clear();
        calendarCardEntityDaoConfig.getIdentityScope().clear();
    }

    public PedometerCardEntityDao getPedometerCardEntityDao() {
        return pedometerCardEntityDao;
    }

    public CalendarCardEntityDao getCalendarCardEntityDao() {
        return calendarCardEntityDao;
    }

}
