package com.lost.zou.pedometer.model.model.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PedometerCardLog".
 */
public class PedometerCardEntity {

    private Long id;
    private Double calories;
    /** Not-null value. */
    private String date;
    private Integer stepCount;
    private Double distanceInMeters;
    private String description;
    private Integer targetStepCount;
    private Integer status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PedometerCardEntity() {
    }

    public PedometerCardEntity(Long id) {
        this.id = id;
    }

    public PedometerCardEntity(Long id, Double calories, String date, Integer stepCount, Double distanceInMeters, String description, Integer targetStepCount, Integer status) {
        this.id = id;
        this.calories = calories;
        this.date = date;
        this.stepCount = stepCount;
        this.distanceInMeters = distanceInMeters;
        this.description = description;
        this.targetStepCount = targetStepCount;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getCalories() {
        return calories;
    }

    public void setCalories(Double calories) {
        this.calories = calories;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getStepCount() {
        return stepCount;
    }

    public void setStepCount(Integer stepCount) {
        this.stepCount = stepCount;
    }

    public Double getDistanceInMeters() {
        return distanceInMeters;
    }

    public void setDistanceInMeters(Double distanceInMeters) {
        this.distanceInMeters = distanceInMeters;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTargetStepCount() {
        return targetStepCount;
    }

    public void setTargetStepCount(Integer targetStepCount) {
        this.targetStepCount = targetStepCount;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
